---

- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Install packages
  ansible.builtin.package:
    name: '{{ avahi_packages }}'
    state: present

- name: Enable options
  ansible.builtin.replace:
    path: '{{ avahi_conf_path }}'
    regexp: '^#?{{ item }}=(?:yes|no)$'
    replace: '{{ item }}=yes'
  loop: '{{ avahi_enable_options }}'
  register: avahi_options_enabled

- name: Disable options
  ansible.builtin.replace:
    path: '{{ avahi_conf_path }}'
    regexp: '^#?{{ item }}=(?:yes|no)$'
    replace: '{{ item }}=no'
  loop: '{{ avahi_disable_options }}'
  register: avahi_options_disabled

- name: Restart avahi-daemon if config changes
  ansible.builtin.systemd:
    name: avahi-daemon
    state: restarted
    daemon_reload: true
    enabled: yes
  when: avahi_options_enabled.changed or avahi_options_disabled.changed