---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: joepublic/molecule-ubuntu:20.04
    privileged: true
    command: /lib/systemd/systemd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  options:
    vvv: True
#lint: |
#  set -e
#  yamllint .
#  ansible-lint .
verifier:
  name: ansible
