---
# This is a playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Get Systemd status of avahi-service
      ansible.builtin.service_facts:
      register: service_facts

    - name: Assert service is running
      ansible.builtin.assert:
        that:
          - "{{ service_facts.ansible_facts.services[service].state in ['running', 'started'] default(False) }}"
        success_msg: "Service {{ service }} is {{ service_state }}"
        fail_msg: "Service {{ service }} is not {{ service_state }}: {{ service_facts | to_nice_yaml }}"
      loop:
        - avahi-daemon
        - avahi-daemon.service
      loop_control:
        loop_var: service
        label: "{{ service }}"

